In [22]:
b = [None, None, None]  # 3명의 데이터를 저장할 리스트

for human_count in range(3):
    Name = input("이름을 입력하세요: ")
    Sex = input("성별을 입력하세요: ")
    Age = input("나이를 입력하세요: ")

    a = [Name, Sex, Age]  # 한 명의 데이터를 리스트로 저장
    b[human_count] = a  # b의 해당 인덱스에 저장

# 입력된 정보 출력
for i in range(3):
    print("사람", i+1, "의 이름은", b[i][0], "성별은", b[i][1], "나이는", b[i][2], "입니다.")


#enumerate, #str.format() 공부하자

이름을 입력하세요: 홍길동
성별을 입력하세요: 김영희
나이를 입력하세요: 23
이름을 입력하세요: 32
성별을 입력하세요: 14
나이를 입력하세요: 43
이름을 입력하세요: 544
성별을 입력하세요: 32
나이를 입력하세요:
사람 1 의 이름은 홍길동 성별은 김영희 나이는 23 입니다.
사람 2 의 이름은 32 성별은 14 나이는 43 입니다.
사람 3 의 이름은 544 성별은 32 나이는  입니다.